import { Router, createCors, error, json } from "itty-router";
import { Env } from "..";
import {
	latestReleases,
	listReleases,
	recentReleases,
	diffReleases,
} from "./v2/releases";
import { githubReleaseWebhookEvent } from "./v2/webhooks";
// import { bulkInsertReleases } from "../crons/cron-handler";

// TODO - create our own middleware so we can have a regex for origins (generated by cloudflare pages deploys)
const { preflight, corsify } = createCors({
	origins: ["pcsx2.net"],
	methods: ["GET", "POST"],
});

const routerV2 = Router();

// Add GET endpoints for cron endpoints when running locally to provide an easy way to test
routerV2
	// embed preflight upstream to handle all OPTIONS requests
	.all("*", preflight)
	// .get("/cron/bulkInsertReleases", bulkInsertReleases)
	.get("/v2/releases/latest", latestReleases)
	.get("/v2/releases/recent", recentReleases)
	.get("/v2/releases/changelog", diffReleases)
	// TODO - add searching capabilities, alongside frontend components
	// .get("/v2/releases/search", searchReleases)
	.get("/v2/releases", listReleases)
	.post("/v2/webhooks/githubReleaseEvent", githubReleaseWebhookEvent)
	.get("*", () => new Response("Not found", { status: 404 }));

export const handleRequest = (
	request: Request,
	env: Env,
	ctx: ExecutionContext
) =>
	routerV2
		.handle(request, env, ctx)
		.then(json)
		// embed corsify downstream to attach CORS headers
		.then(corsify)
		.catch(error);
